language: c

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libc6-dev
      - libgc-dev
      - xutils-dev

sudo: false

script:
  - make clean
  - make depend
  - make
  - make bench
  - make test

