language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
	  - xutils-dev

sudo: false

script:
  - make clean
  - make depend
  - make
  - make test
  - make bench

